### ISSUE TITLE
Arbeitsbreite anzeigen

### ISSUE THREAD

**Issue by johnwayne1930** [Achimobil/FS22_InfoDisplayExtension#11]
Als konsequente Fortführung der Anzeige von Leistungsdaten der Maschinerie, könnte auch die Arbeitsbreite von Anbaugeräten oder Selbstfahrern angezeigt werden.
Damit würde man sich sparen immer im Shop nachsehen zu müssen, oder im Falle der Verwendung anderer Mods welche das HUD erweitern, einsteigen zu müssen um die Arbeitsbreite eines Geräts herauszufinden.

**Comment by Achimobil** [comment]
Interessante idee, müsste man mal schauen ob auch das verfügbar ist so wie ich das auslese ;)
