### ISSUE TITLE
Keine Leistungsdaten bei John Deere 710

### ISSUE THREAD

**Issue by johnwayne1930** [Achimobil/FS22_InfoDisplayExtension#12]
Beim FarmCon22 - John Deere 710 werden keine Leistungskenndaten angezeigt.

![fsScreen_2023_06_17_17_44_48](https://github.com/Achimobil/FS22_InfoDisplayExtension/assets/7887254/d3bc34fc-cb5d-433d-bdc2-ee5f5673ed88)

Bei dem FarmCon22 - John Deere 5090M allerdings schon.

![fsScreen_2023_06_17_17_45_03](https://github.com/Achimobil/FS22_InfoDisplayExtension/assets/7887254/655b8261-d52a-449e-83a2-b6175064c911)

**Comment by Achimobil** [comment]
Link vom Modhub wo ich den her bekomme wäre hilfreich ;)

**Comment by johnwayne1930** [comment]
Klar hier bitte
https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=250015&title=fs2022

**Comment by Achimobil** [comment]
![Image](https://github.com/Achimobil/FS22_InfoDisplayExtension/assets/65055783/2609463f-ca65-4dd3-b783-bf9f7b088189)

Der Modder, in dem Fall ja Giants, hat beim Motor keine Leistung eingetragen. Das was auf dem Bild ist habe ich zum testen eingetragen. Somit gibt es zum Motor keine PS Angabe und deshalb kann ich auch nichts anzeigen.

**Comment by johnwayne1930** [comment]
Ich werde das bei GIANTS als Bug melden, auch wenn ich mir wenig davon erhoffe.

**Comment by Achimobil** [comment]
Mehr als versuchen kann man es nicht, habe da noch viele Tickets offen
