### ISSUE TITLE
[Suggestion]: Add information for DEF

### ISSUE THREAD

**Issue by westor7** [Achimobil/FS22_InfoDisplayExtension#14]
Hello,

Can you add support for the following mod to display the DEF (ADBlue) informations like it does for Diesel?

Mod: https://www.farming-simulator.com/mod.php?lang=en&country=rs&mod_id=236483

![](https://i.imgur.com/Gf5nXrz.jpeg)

![](https://i.imgur.com/bV2PJVR.jpeg)

- Thanks!

**Comment by Achimobil** [comment]
I think I can, but I will not do that as long the mod in the ModHub is broken.
When it is fixed in the ModHub you are free to reopen the ticket

**Comment by westor7** [comment]
That mod in modhub is not broken, i keep using it all the time and is working perfectly.

**Comment by Achimobil** [comment]
```
2023-06-27 18:12   Error: Invalid customEnvironment given for SpecializationManager.addSpecialization. Should be a string or nil.
2023-06-27 18:12 LUA call stack:
  dataS/scripts/mods.lua (466) : printCallstack
  =E:/LS22Profile/HofBergmann/mods/FS22_DefPack/scripts/RegisterSpecialization.lua (80) : addSpecialization
  =[C] (4294967295)
  dataS/scripts/mods.lua (417) : source
  dataS/scripts/mods.lua (918) : source
  dataS/scripts/xml/XMLFile.lua (296) : closure
  dataS/scripts/mods.lua (915) : iterate
  dataS/scripts/gui/MPLoadingScreen.lua (765) : loadMod
  dataS/scripts/misc/AsyncTaskManager.lua (41) : lambda
  dataS/scripts/misc/AsyncTaskManager.lua (120) : runLambda
  dataS/scripts/misc/AsyncTaskManager.lua (146) : runTopTask
  dataS/scripts/main.lua (1221) : update
2023-06-27 18:12   Error: Too many arguments for SpecializationManager.addSpecialization. (Arguments should be: name, className, filename, customEnvironment)
2023-06-27 18:12 LUA call stack:
  dataS/scripts/mods.lua (471) : printCallstack
  =E:/LS22Profile/HofBergmann/mods/FS22_DefPack/scripts/RegisterSpecialization.lua (80) : addSpecialization
  =[C] (4294967295)
  dataS/scripts/mods.lua (417) : source
  dataS/scripts/mods.lua (918) : source
  dataS/scripts/xml/XMLFile.lua (296) : closure
  dataS/scripts/mods.lua (915) : iterate
  dataS/scripts/gui/MPLoadingScreen.lua (765) : loadMod
  dataS/scripts/misc/AsyncTaskManager.lua (41) : lambda
  dataS/scripts/misc/AsyncTaskManager.lua (120) : runLambda
  dataS/scripts/misc/AsyncTaskManager.lua (146) : runTopTask
  dataS/scripts/main.lua (1221) : update
```
Direct on game start and one mod with this error can break other script mods.
I think he has made a fix on his GitHub, but I will not do anything as long as this is not usable from ModHub

**Comment by westor7** [comment]
Yeah this error is fixed in his Gitlab latest release. but indeed it differs from the modhub one. but even this error when appearing the mod keeps running well without any noticeable issues and i know a lot of people that keep using it. but ok i understand your point. thanks anyway.

**Comment by Achimobil** [comment]
And I know a lot of users which had problems with my script mods with such an error in the log from a mod and removing solves the problem. So I will not discuss this. When it is error free in the ModHub I can add it, but not as long as this error is in the official version. 
When a modder decide to publish in the modhub I expect that he keeps them running or remove them when not.
