### ISSUE TITLE
Anzeige funktioniert nicht korrekt bei dem "Überdachtes Haufenlager" Mod

### ISSUE THREAD

**Issue by Timmeey86** [Achimobil/FS22_InfoDisplayExtension#15]
Hi,

erstmal vielen Dank für den Mod, er ist sehr hilfreich und funktioniert grundsätzlich sehr gut. Über eine einzige Ausnahme sind wir gestolpert:

Der [Überdachtes Haufenlager Mod](https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=235666) bringt von jedem Lagertyp jeweils drei Gebäude mit unterschiedlichen Füllmengen mit. Es scheint so, als ob Info Display Extension dort immer nur die kleinste Füllmenge anzeigt, egal welches Gebäude man setzt.

Reproducer:
- Neues Spiel starten mit nur diesem Mod und Info Display Extension
- Ein beliebiges Haufenlager für 80.000€ setzen (sollte 10.000.000l Kapazität haben)
- Hinlaufen und Kapazität betrachten

Hier ein Screenshot, nachdem mehr eingefüllt wurde:
![grafik](https://github.com/Achimobil/FS22_InfoDisplayExtension/assets/10223149/129b127e-aec5-4f9e-9bf1-77baf0f55783)

**Comment by Achimobil** [comment]
Ist ein Fehler im Mod. Der Storage Node hat keine Kapazität eingetragen und mein Mod zeigt ja nur an, was das Spiel an info hat.
Oder einfacher ausgedrückt: 
der storage node hat eine property die capacity heißt. Ist diese nicht eingetragen ist der default 100000.
Und da er nicht eingetragen ist, hat das lager eine Kapazität von 100000 und die wird auch angezeigt.

**Comment by Timmeey86** [comment]
Bedeutet das, der Lager Mod bräuchte nicht nur eine Capacity pro Fill Type, sondern auch noch ein `capacity = ...` im `<storage>` Element?
![grafik](https://github.com/Achimobil/FS22_InfoDisplayExtension/assets/10223149/55c479f7-cb37-4b39-846f-e6c03d528a2d)

**Comment by Achimobil** [comment]
Richtig, wenn nichts angegeben ist, dann nimmt giants da die 100000 als default und die Zeige ich da an.

**Comment by Timmeey86** [comment]
Alles klar, ich wollte den Mod und die Kapazitäten eh anpassen ;-)
