### ISSUE TITLE
1.6.0.6 Pre-release Lua Error mit PnH Fermenter

### ISSUE THREAD

**Issue by johnwayne1930** [Achimobil/FS22_InfoDisplayExtension#17]
[log_InfoDisplay_Lua.txt](https://github.com/Achimobil/FS22_InfoDisplayExtension/files/13325393/log_InfoDisplay_Lua.txt)

Version 1.6.0.6 Pre-release

Lua Fehler im Log im unmittelbaren Umkreis eines Pumps and Hoses Fermenter (in meinem Fall Fermenter 30m).
Auch das Info Display wird nicht angezeigt in der nähe des Fermenters.

**Comment by Achimobil** [comment]
Der fehler kommt nicht vom Info Display Mod, da muss ein anderer mod die anzeige verändert und die sorgt dafür dass der info display die parameter falsch bekommt. Ist auf der Hof Bergmann auch so und liegt da am produktionsskript von GTX. Woran es bei dir liegt kann ich nicht sagen. Es kann auch sein das PnH erst noch ein Update benötigt.
Da das aber eine DLC ist kann ich da nicht rein schauen. Die 1.6.0.6 ist angepasst an den neuen Patch von Giants.
Bitte an den Hersteller wenden.

**Comment by Achimobil** [comment]
Aber gerade trotzdem mal geschaut. Vanilla karte und nur PnH macht auch den fehler, nur das mein mod nicht im stacktrace steht

**Comment by Achimobil** [comment]
Gerade von Creative gehört: Ist bekannt und wird behoben
