### ISSUE TITLE
[Enhancement] BR translation

### ISSUE THREAD

**Issue by Myiamoto86** [Achimobil/FS22_InfoDisplayExtension#18]
Dear,

I hope once again to be able to contribute to your work.

Please find attached the document containing the translation BR of your mod.

Hugs.

[translation_br.txt](https://github.com/Achimobil/FS22_InfoDisplayExtension/files/13368943/translation_br.txt)

**Comment by Achimobil** [comment]
Thanks, I will use that when the next update is on the go.

**Comment by Achimobil** [comment]
you can use the new pre release: https://github.com/Achimobil/FS22_InfoDisplayExtension/releases/tag/1.7.0.1
