### ISSUE TITLE
French translation.

### ISSUE THREAD

**Issue by txadi** [Achimobil/FS22_InfoDisplayExtension#19]
Hello,
I took the liberty of translating into the French version. If you ever want to include it in a release, it would be nice for the French community. Thank you.
Txadi
[translation_fr.xml.zip](https://github.com/Achimobil/FS22_InfoDisplayExtension/files/13424002/translation_fr.xml.zip)

**Comment by Achimobil** [comment]
I add them to the main branch and they will be in the next release, thanks

**Comment by Achimobil** [comment]
you can use the new pre release: https://github.com/Achimobil/FS22_InfoDisplayExtension/releases/tag/1.7.0.1
