### ISSUE TITLE
VehicleType info

### ISSUE THREAD

**Issue by cagatay117** [Achimobil/FS22_InfoDisplayExtension#23]
Hello, could we add vehicle type name in the HUD? when we approach the trailer, attachment, vehicle etc. it will show it's type name, e.g bale wrapper, mower, auger wagon, cutter, tedder, tractor (I know tractor is obvious but you know, just to be consistent), harvester, front loader, roller, etc...

It will look like this:
![image](https://github.com/Achimobil/FS22_InfoDisplayExtension/assets/6120852/4b3926f0-185b-4e33-aba8-ba0333deeb36)

Is it possible?

**Comment by Achimobil** [comment]
The problem here is that there is not real type. in vehicles you can mit all types as you wish. you can make a vehicle be a plow, tedder and trailer the same time

**Comment by cagatay117** [comment]
I thought maybe it can be read from the vehicle xml file
`<vehicle type="spreader" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../shared/xml/schema/vehicle.xsd">`
_Spreader_ in this example.
I don't know if it will be that informative but for a newbie like me it would mean a lot. I have trouble distinguishing tools. When we  are more experienced, we can disable this info from Info Display Extension options.

**Comment by Achimobil** [comment]
This is also an information every modder can define self. There are some types predefined but the most used types are custom per mod

**Comment by cagatay117** [comment]
I understand. Thank you for your help.

**Comment by Achimobil** [comment]
No Problem. I will leave this open as idea, perhaps I got an idea of how to make this in the future

**Comment by cagatay117** [comment]
Thank you.
Maybe you can implement something like this. Not exactly but close would be perfect.

![image](https://github.com/Achimobil/FS22_InfoDisplayExtension/assets/6120852/4330e579-79fb-42c4-a1a9-f25651e8ef0c)
The info is taken from the shop screen as you know. I hope I am not being too much, this is just an idea. You can make better or nothing at all, you are the boss. :)

**Comment by Achimobil** [comment]
This will not happen, because this is a extension mod to extend the info box of giants, not to replace it with something

**Comment by Achimobil** [comment]
Im 22er gibt es keine Features mehr. Deshalb close ich das hier
