### ISSUE TITLE
Is it possible to add a Weights/Gewichte line for attachments?

### ISSUE THREAD

**Issue by vitalii2011** [Achimobil/FS22_InfoDisplayExtension#25]
- For example from: `<combination filterCategory="weights" filterSpec="weight" filterSpecMin="600" filterSpecMax="700"/>`  
"Weights     600-700 kg".
- Russian translation: "Противовесы". )

**Comment by Achimobil** [comment]
You mean the weight of the vehicle? but the weight should be shown default in the second line from below
![image](https://github.com/Achimobil/FS22_InfoDisplayExtension/assets/65055783/ab6c386a-de3b-4f45-b92a-9432d865d190)

**Comment by vitalii2011** [comment]
https://github.com/Achimobil/FS22_InfoDisplayExtension/assets/41552153/2a754d41-1661-4904-a7c2-f0ac41f418f3

![2024_02_08_10_55_13](https://github.com/Achimobil/FS22_InfoDisplayExtension/assets/41552153/e5d20f83-ce30-46e2-8628-bd1905551070)

**Comment by Achimobil** [comment]
Oh, some kind of suggested weight for usage. 
I will take a look if showing is possible in the future

**Comment by EnzoAero** [comment]
I am unable to see weights at all in my info display.was muss ich tun?

**Comment by Achimobil** [comment]
Please read the ticket and the ticket state. 
Then your question is answered from this self.

**Comment by Achimobil** [comment]
Im 22er gibt es keine Features mehr. Deshalb close ich das hier
