### ISSUE TITLE
New version coming?

### ISSUE THREAD

**Issue by Ferchu425** [Achimobil/FS22_InfoDisplayExtension#29]
Hi there, I was thinking on contributing the spanish translations but I saw they are already in the repository :) Are you thinking on a new release? (saw other changes here also).

Thank you for your work !!

**Comment by Achimobil** [comment]
Currently I am busy with many other project, so a modhub release is not planed when no errors occour.
But the Version with spain in you can download here in the releases where the spain is already in: https://github.com/Achimobil/FS22_InfoDisplayExtension/releases

Or do you mean something else?

**Comment by Ferchu425** [comment]
Ok, thank you, I will download that "pre-release" and use it. Thank you
