### ISSUE TITLE
Crashing FS25 reading tree data.

### ISSUE THREAD

**Issue by FJH-Photurnal** [Achimobil/FS22_InfoDisplayExtension#31]
On both Riverbend and Hutan maps my player POV froze approaching a tree to check its information. The log reports "getn expects a table, found "NIL'' " listing InfoDisplayExtension.lua line 848. 
Both times I planted OAK trees and it may be a fault in the game but I confirmed it by reloading the savegame without InfoDisplayExtension  active and could not reproduce the frozen POV. I hope this is a simple fix because I appreciate both the mod and the work you put into it. 
Thank you.

**Comment by Achimobil** [comment]
Then search for the big in the correct repro and you will find that this is already known and fixed and send to modhub and published today ;)
