### ISSUE TITLE
Error in Beta 3 beim rantreten an ein Anbaugerät

### ISSUE THREAD

**Issue by PanikPitty** [Achimobil/FS22_InfoDisplayExtension#6]
Mit der neusten Beta der InfoDisplayExtension habe ich einen Error mit LUA in der Log, sobald ich an ein Anbaugerät herantrete und das Info Display unten rechts erscheint.
Dabei spielt es keine Rolle, was es für ein Anbaugerät ist. Auch Anhänger und Ladewagen etc. sind davon betroffen.

Error: Running LUA method 'update'.
C:/Users/danie/Documents/My Games/FarmingSimulator2022/mods/FS22_InfoDisplayExtension/InfoDisplayExtension.lua:832: attempt to index local 'powerConfig' (a nil value)

Anbei die Log auf der Elmcreek ohne weitere Mods.
[log.txt](https://github.com/Achimobil/FS22_InfoDisplayExtension/files/11453869/log.txt)

**Comment by Achimobil** [comment]
Also ich bin jetzt an jedes Anbaugerät rangetreten, dass ich auch meinem Spielstand habe und habe bei keinem eine Fehlermeldung bekommen. Im Testspielstand mit nur wenigen mods hingegen bekam ich den Fehler bei meinem Strautmann, somit konnte ich es nur da nachvollziehen, warum ist mir allerdings schleierhaft
