### ISSUE TITLE
Fehlende Informationen im Display auf dem Deadicated Server

### ISSUE THREAD

**Issue by PapaTim68** [Achimobil/FS22_InfoDisplayExtension#8]
Ich habe festgestellt auf unserem Deadicated Server manche Informationen fehlen, die im Singleplayer angezeigt werden. Aufgefallen ist es spezifisch bei Bäumen.
Hier ein Screenshot vom Server:
![grafik](https://github.com/Achimobil/FS22_InfoDisplayExtension/assets/29522870/38f818ee-ea68-44bb-b594-6dd77ab76cbc)

Gleiche Stelle, gleiches Save im SP:
![grafik](https://github.com/Achimobil/FS22_InfoDisplayExtension/assets/29522870/a0532310-9d86-4af2-a0e9-c77d1568a409)

Ich hoffe, du kannst das Problem beheben.

Grüße PapaTim

**Comment by Achimobil** [comment]
Nein, das kann nicht behoben werden. Aus Performancegründen werden die zigtausend Bäume nur auf dem Host gehalten und nicht syncronisiert zu den clients. Deshalb kann auf einem Client das nicht angezeigt werden. Das zu syncronisieren habe ich versucht. Spielen ist dann nicht mehr möglich.
